// Code generated by logcopter-gen; DO NOT EDIT.

package emrichen

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.go-emrichen.pkg.emrichen")
