name: Dependency Scanning

on:
  push:
    branches: [main] # Adjust if your main branch has a different name
  pull_request:
    branches: [main] # Adjust if your main branch has a different name
  schedule:
    - cron: "0 0 * * 0" # Run weekly on Sunday at midnight

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high

  govulncheck:
    name: Go Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # Ensure this matches your project's Go version

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...

  nancy:
    name: Nancy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # Ensure this matches your project's Go version

      - name: Install Nancy
        run: go install github.com/sonatype-nexus-community/nancy@latest

      - name: Run Nancy
        run: go list -json -deps ./... | nancy sleuth

  gosec:
    name: GoSec Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # Ensure this matches your project's Go version

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          # Adjust exclusions based on your project's needs
          args: -exclude=G101,G304,G301,G306,G204 -exclude-dir=.history ./...
