name: Secret Scanning

on:
  push:
    branches: [ main ] # Adjust if your main branch has a different name
  pull_request:
    branches: [ main ] # Adjust if your main branch has a different name

jobs:
  trufflehog:
    name: TruffleHog Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for TruffleHog to scan history

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD 